language: node_js
node_js:
  - "7"
  - "6"
  - "4"
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - gulp coveralls
script:
  - gulp eslint
  - npm test && _FORCE_LOGS=1 npm run e2e-test
