language: node_js
node_js:
  - "10"
  - "12"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
env:
  - COMMAND="npm test"
  - COMMAND="npm run e2e-test" _FORCE_LOGS=1
services:
  - xvfb
after_success:
  - npm run coverage
script: $COMMAND
